### ISSUE TITLE
Support for self signed certificates

### ISSUE THREAD

**Issue by m3talsmith** [bserdar/took#1]
Currently when the oidc server you're authenticating against is using a self signed certificate, you'll get the error: `x509: certificate signed by unknown authority`

## Steps to reproduce

```bash
took add oidc-direct-access -n <name> -c <clientID> -s <clientSecret> -u <oidcServer>
# ...
took token <name>
# Get <oidcServer>: x509: certificate signed by unknown authority
```

**Comment by bmstrach** [comment]
When trying to produce tokens for the following username with certain special characters, I get an error
Ex.
]$  took token dev SLAC_Users_With_#!&@'[]{.}`+-_?_3
-bash: !: event not found
The user is an authenticated user in the app

FWIW the tool worked for the following user with special characters:
took token dev #B@rry&!@!en

**Comment by bserdar** [comment]
Added -k flag to disable tls cert validation
