### ISSUE TITLE
Took Insecure Mode Is Insecure

### ISSUE THREAD

**Issue by sgayou** [bserdar/took#10]
This one is a bit obvious. Insecure mode disables certificate chain and host name verification which is dangerous / a bad habit.

I'm guessing this is used for development or testing, but it seems like a poor practice and could lead to insecure setups. Tokens should never be sent to untrusted TLS endpoints. Instead, if a self-signed cert needs to be used, that should be installed in the operating systems cert store.

Could this be put into a development only build, i.e. require a specific flag to build this into the binary? Ideally this would not be a default. If not, could we print an annoying warning every time a took request is sent to an insecure endpoint, else prompt the user again? ("Are you absolutely sure you want to transmit tokens/credentials to an untrusted endpoint? An attacker could man-in-the-middle this connection and steal tokens/usernames/passwords" -- something like that)

**Comment by bserdar** [comment]
This and #9 is useful for development and testing. Maybe we can make the support more explicit for these? How about we enable -k and http endpoints only if you run took through a link, like took-insecure? So took token -k would fail, but took-insecure token -k would work?

**Comment by sgayou** [comment]
I like that solution -- insecure in name will hopefully get it across to a user that something bad is potentially happening. Will make testing and setup a bit more friendly as well.

**Comment by m3talsmith** [comment]
I'll give my +1 to having a took-insecure build for dev and test work. Do we need the -k on that build, or do we assume it?

**Comment by bserdar** [comment]
'secure' branch now has code that enables -k flag only if took is run with "-insecure" in its name.

**Comment by bserdar** [comment]
Fixed as of d80093a
