### ISSUE TITLE
URL for authentication not working when using an added server configuration

### ISSUE THREAD

**Issue by bmstrach** [bserdar/took#16]
@bserdar Not sure if this is an error on my part, but I'll explain.
When I add a token using the following command:
Not sure if I should put the client secret and id here, but I have them if needed.
took add oidc -n testing-prod-2 -s <client secret> -c <client id> -u https://sso.redhat.com/auth/realms/3scale/ -b https://api.access.redhat.com/management
[Note: I've also eliminated the -b and produced the same results]
And then I run took token for my account (credentials also proved upon request), I get here:
"Go to this URL to authenticate "
When I try to visit that url, I get an invalid parameter error:
https://sso.redhat.com/auth/realms/3scale/protocol/openid-connect/auth?access_type=online&client_id=f119df48&redirect_uri=https%3A%2F%2Fapi.access.redhat.com%2Fmanagement&response_type=code&scope=openid&state=eqo_xX3VBkWhAvI1uy9r3INkK8F7aNMf_XepVujrY-4%3D

**Comment by bserdar** [comment]
Missing callback url in config.
