### ISSUE TITLE
Cannot get token for user with certain special characters

### ISSUE THREAD

**Issue by bmstrach** [bserdar/took#2]
When trying to produce tokens for the following username with certain special characters, I get an error
Ex.
]$  took token dev SLAC_Users_With_#!&@'[]{.}`+-_?_3
-bash: !: event not found
The user is an authenticated user in the app

FWIW the tool worked for the following user with special characters:
took token dev #B@rry&!@!en

**Comment by bserdar** [comment]
This is not a bug. You need some escaping to get that username to work with the shell:

took token qa SLAC_Users_With_\#\!\&@\'\[\]\{.\}\`+-_\?_3
