### ISSUE TITLE
Took Support for HTTP 

### ISSUE THREAD

**Issue by sgayou** [bserdar/took#9]
Took supports HTTP endpoints / OIDC flows. Thus, if someone configures took with an endpoint or callback url using http, there is a possibility of secrets, tokens, and username/passwords being transmitted in plain-text.

The spec seems to suggest (I am unclear if it requires) TLS. See https://tools.ietf.org/html/rfc6749 10.5:

```
   The transmission of authorization codes SHOULD be made over a secure
   channel, and the client SHOULD require the use of TLS with its
   redirection URI if the URI identifies a network resource.  Since
   authorization codes are transmitted via user-agent redirections, they
   could potentially be disclosed through user-agent history and HTTP
   referrer headers.
```

Detecting and blocking non-HTTPS URLs seems like a great way to prevent users from shooting themselves in the foot.

Wireshark of plaintext password grant request:
```
HTML Form URL Encoded: application/x-www-form-urlencoded
    Form item: "client_id" = "<censored>"
    Form item: "client_secret" = "<censored>"
    Form item: "grant_type" = "password"
    Form item: "password" = "<censored>"
    Form item: "scope" = "openid"
    Form item: "username" = "<censored>"
```

**Comment by bserdar** [comment]
Fixed as of d80093a

This is only allowed when run as took-insecure
